[terminal]
vt = 1

[default_session]
command = "tuigreet -t -r --remember-session --asterisks --theme text=yellow;container=black;border=yellow;prompt=green;input=purple;action=yellow --cmd Hyprland"
user = "greeter"
