# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
	"system",
	"users/pohlrabi",
    "commons/apps",
]

[managers.system]
items = []

[managers.flatpak]
items = []

[managers.cargo]
items = []
