[managers.system]
items = [
	# tldr / man page
	"tealdeer",

	# browser
	"qutebrowser",

	# git
	"lazygit",

	# file browser
	"yazi",
	"fzf",

	# zsh theme and plugins
	"starship",

	# font
	"ttf-firacode-nerd",
    "ttf-koruri",

    # nodejs
    "nodejs",
    "unzip",
    "npm",
    "go",

    # app runner
    "anyrun-git",

    # theme
    "ags-hyprpanel-git",
    ## dependencies
    "swww",
	"brightnessctl",
    "pacman-contrib",
    "power-profiles-daemon",
    "grimblast",
    "gpu-screen-recorder",
    "hyprpicker",
    "hypridle",
    "btop",
    "matugen",
    "libgtop",
    "bluez",
    "bluez-utils",
    "networkmanager",
    "dart-sass",
	"wl-clipboard",
    "upower",
    "gvfs",
    "xdg-desktop-portal-hyprland",

	# wm
	"hyprland",
    ## dependencies
	"hyprpolkitagent",
	"qt5-wayland",
	"qt6-wayland",
	"hyprcursor",
	"kitty",

    # keybind
    "wev",
    "google-chrome",

    # mpv
    "mpv",
    "svp-bin",
    "yt-dlp",

    # japanese input
    "fcitx5-im",
    "fcitx5-mozc",

    # flex
    "fastfetch",
]
